-- Server-side question generation and score verification for multiplayer.
--
-- Closes the competitive integrity gap: questions are now generated by the
-- server at match creation time, and scores are computed server-side from
-- raw answers rather than trusting client-reported scores.
--
-- Changes:
--   1. Creates a level_configs table mirroring the JS SOROBAN_LEVELS.
--   2. Creates create_match(config) RPC that generates questions server-side.
--   3. Rewrites update_match_progress to validate answers vs stored questions
--      and compute scores on the server (player_score param removed).

-- === 1. Level configs lookup table ===

CREATE TABLE IF NOT EXISTS level_configs (
  level INT PRIMARY KEY,
  operations TEXT NOT NULL,
  digit_count INT NOT NULL,
  row_count INT NOT NULL,
  target_qpm INT NOT NULL,
  target_accuracy INT NOT NULL
);

INSERT INTO level_configs (level, operations, digit_count, row_count, target_qpm, target_accuracy) VALUES
  (1,  'addition',      1, 3, 10, 90),
  (2,  'mixed_add_sub', 1, 4, 15, 90),
  (3,  'mixed_add_sub', 2, 4, 20, 88),
  (4,  'mixed_add_sub', 2, 5, 25, 85),
  (5,  'mixed_add_sub', 3, 5, 30, 85),
  (6,  'mixed_add_sub', 3, 6, 35, 83),
  (7,  'mixed_add_sub', 4, 6, 40, 80),
  (8,  'mixed_all',     4, 7, 45, 80),
  (9,  'mixed_all',     5, 7, 50, 78),
  (10, 'mixed_all',     5, 8, 60, 75)
ON CONFLICT (level) DO NOTHING;

-- === 2. Question generator helpers ===

CREATE TABLE IF NOT EXISTS mult_difficulty (
  level INT PRIMARY KEY,
  multiplicand_min INT NOT NULL,
  multiplicand_max INT NOT NULL,
  multiplier_min INT NOT NULL,
  multiplier_max INT NOT NULL
);

INSERT INTO mult_difficulty (level, multiplicand_min, multiplicand_max, multiplier_min, multiplier_max) VALUES
  (1,  10,    99,    2,  9),
  (2,  100,   999,   2,  9),
  (3,  100,   999,   2,  9),
  (4,  1000,  9999,  2,  9),
  (5,  1000,  9999,  2,  9),
  (6,  100,   999,   11, 99),
  (7,  1000,  9999,  11, 99),
  (8,  10000, 99999, 2,  9),
  (9,  10000, 99999, 11, 99),
  (10, 10000, 99999, 11, 99)
ON CONFLICT (level) DO NOTHING;

CREATE TABLE IF NOT EXISTS div_difficulty (
  level INT PRIMARY KEY,
  dividend_min INT NOT NULL,
  dividend_max INT NOT NULL,
  divisor_min INT NOT NULL,
  divisor_max INT NOT NULL
);

INSERT INTO div_difficulty (level, dividend_min, dividend_max, divisor_min, divisor_max) VALUES
  (1,  10,      99,       2,  9),
  (2,  100,     999,      2,  9),
  (3,  100,     9999,     2,  9),
  (4,  1000,    9999,     2,  9),
  (5,  1000,    99999,    2,  9),
  (6,  10000,   99999,    2,  9),
  (7,  10000,   99999,    11, 99),
  (8,  10000,   999999,   11, 99),
  (9,  100000,  999999,   11, 99),
  (10, 100000,  9999999,  11, 99)
ON CONFLICT (level) DO NOTHING;

-- Generate a single add_sub question using the same algorithm as the JS generator
CREATE OR REPLACE FUNCTION gen_add_sub_question(
  p_level INT
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  lc RECORD;
  max_val INT;
  is_addition_only BOOLEAN;
  first_operand INT;
  running_total INT;
  operand INT;
  operands JSONB := '[]'::jsonb;
  i INT;
  min_first INT;
  first_max INT;
  want_subtract BOOLEAN;
  can_subtract BOOLEAN;
  room_to_add INT;
BEGIN
  SELECT * INTO lc FROM level_configs WHERE level = p_level;
  max_val := power(10, lc.digit_count)::int - 1;
  is_addition_only := lc.operations = 'addition';

  -- First operand (matches pickInitialOperand in JS)
  min_first := CASE WHEN is_addition_only THEN 1 ELSE greatest(1, floor(max_val * 0.3)::int) END;
  first_max := CASE WHEN is_addition_only THEN greatest(min_first, max_val - (lc.row_count - 1)) ELSE max_val END;
  first_operand := greatest(min_first, floor(random() * greatest(first_max, 1))::int + 1);

  running_total := first_operand;
  operands := operands || to_jsonb(first_operand);

  -- Subsequent operands (matches pickNextAddSubOperand in JS)
  FOR i IN 2..lc.row_count LOOP
    want_subtract := NOT is_addition_only AND (
      lc.operations = 'subtraction' OR
      lc.operations = 'mixed_all' OR
      (lc.operations = 'mixed_add_sub' AND random() > 0.5)
    );

    can_subtract := NOT is_addition_only AND running_total > 0;
    room_to_add := max_val - running_total;

    IF want_subtract AND can_subtract THEN
      operand := -greatest(1, floor(random() * running_total)::int);
    ELSIF room_to_add >= 1 THEN
      operand := greatest(1, floor(random() * room_to_add)::int);
    ELSIF can_subtract THEN
      operand := -greatest(1, floor(random() * running_total)::int);
    ELSE
      operand := 0;
    END IF;

    running_total := running_total + operand;
    operands := operands || to_jsonb(operand);
  END LOOP;

  RETURN jsonb_build_object(
    'operands', operands,
    'answer', running_total,
    'operation', 'add_sub'
  );
END;
$$;

-- Generate a single multiplication question
CREATE OR REPLACE FUNCTION gen_mult_question(
  p_level INT
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  d RECORD;
  multiplicand INT;
  multiplier INT;
BEGIN
  SELECT * INTO d FROM mult_difficulty WHERE level = p_level;
  multiplicand := d.multiplicand_min + floor(random() * (d.multiplicand_max - d.multiplicand_min + 1))::int;
  multiplier := d.multiplier_min + floor(random() * (d.multiplier_max - d.multiplier_min + 1))::int;
  RETURN jsonb_build_object(
    'operands', jsonb_build_array(multiplicand, multiplier),
    'answer', multiplicand * multiplier,
    'operation', 'multiplication'
  );
END;
$$;

-- Generate a single division question (always exact division)
CREATE OR REPLACE FUNCTION gen_div_question(
  p_level INT
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  d RECORD;
  divisor INT;
  quotient INT;
  quotient_min INT;
  quotient_max INT;
  dividend INT;
BEGIN
  SELECT * INTO d FROM div_difficulty WHERE level = p_level;
  divisor := d.divisor_min + floor(random() * (d.divisor_max - d.divisor_min + 1))::int;
  quotient_min := greatest(2, ceil(d.dividend_min::numeric / divisor)::int);
  quotient_max := greatest(quotient_min, floor(d.dividend_max::numeric / divisor)::int);
  quotient := quotient_min + floor(random() * (quotient_max - quotient_min + 1))::int;
  dividend := divisor * quotient;
  RETURN jsonb_build_object(
    'operands', jsonb_build_array(dividend, divisor),
    'answer', quotient,
    'operation', 'division'
  );
END;
$$;

-- Generate a full set of multiplayer questions (server-side)
CREATE OR REPLACE FUNCTION generate_multiplayer_questions(
  p_level INT,
  p_question_type TEXT,
  p_count INT DEFAULT 60
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  questions JSONB := '[]'::jsonb;
  q JSONB;
  i INT;
  level_adjusted INT;
BEGIN
  -- Cap level for multiplication/division tables (supports levels 1-10)
  level_adjusted := greatest(1, least(10, p_level));

  FOR i IN 1..p_count LOOP
    IF p_question_type = 'multiplication' THEN
      q := gen_mult_question(level_adjusted);
    ELSIF p_question_type = 'division' THEN
      q := gen_div_question(level_adjusted);
    ELSE
      q := gen_add_sub_question(level_adjusted);
    END IF;
    questions := questions || q;
  END LOOP;

  RETURN questions;
END;
$$;

-- === 3. create_match RPC — generates questions and creates a match in one call ===

CREATE OR REPLACE FUNCTION create_match(
  p_config JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  room_code TEXT;
  v_level INT;
  v_question_type TEXT;
  v_time_limit INT;
  questions JSONB;
  match_id TEXT;
  allowed_types TEXT[] := ARRAY['add_sub', 'multiplication', 'division'];
BEGIN
  -- Validate config
  v_level := (p_config->>'level')::int;
  v_question_type := p_config->>'questionType';
  v_time_limit := COALESCE((p_config->>'timeLimitSeconds')::int, 180);

  IF v_level IS NULL OR v_level < 1 OR v_level > 10 THEN
    RAISE EXCEPTION 'Invalid level: must be 1-10';
  END IF;

  IF v_question_type IS NULL OR NOT (v_question_type = ANY(allowed_types)) THEN
    RAISE EXCEPTION 'Invalid questionType: must be add_sub, multiplication, or division';
  END IF;

  IF v_time_limit < 30 OR v_time_limit > 600 THEN
    RAISE EXCEPTION 'Invalid timeLimitSeconds: must be 30-600';
  END IF;

  -- Rate limit: max 10 match creations per minute per user
  IF NOT check_rate_limit(auth.uid(), 'create_match', 10) THEN
    RAISE EXCEPTION 'Rate limit exceeded. Please slow down.';
  END IF;

  -- Generate room code (6 chars from the same alphabet used client-side)
  room_code := '';
  FOR i IN 1..6 LOOP
    room_code := room_code || substring('ABCDEFGHJKLMNPQRSTUVWXYZ23456789' FROM floor(random() * 29)::int + 1 FOR 1);
  END LOOP;

  -- Generate questions server-side, scaling with the time limit
  questions := generate_multiplayer_questions(v_level, v_question_type, LEAST(400, GREATEST(60, v_time_limit * 2)));

  -- Insert match
  INSERT INTO matches (id, status, is_public, player1_id, questions, config, scores, created_at)
  VALUES (room_code, 'waiting', false, auth.uid(), questions, p_config, '{}'::jsonb, now())
  RETURNING id INTO match_id;

  RETURN jsonb_build_object(
    'match_id', match_id,
    'question_count', jsonb_array_length(questions)
  );
END;
$$;

-- === 4. Updated update_match_progress — computes scores server-side from answers ===
-- player_score parameter removed: the server validates each answer against the
-- stored questions and counts correct ones. The client-provided isCorrect flag
-- is ignored (recomputed server-side). Duplicate questionIndex entries are
-- deduplicated (last value wins).

CREATE OR REPLACE FUNCTION update_match_progress(
  match_id TEXT,
  player_num INT,
  answers JSONB,
  player_done BOOLEAN DEFAULT false
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  m RECORD;
  uid UUID;
  ans_q_idx INT;
  correct_answer INT;
  submitted_answer INT;
  ans_time_taken NUMERIC;
  correct_count INT := 0;
  validated_answers JSONB := '[]'::jsonb;
  dedup_record RECORD;
BEGIN
  uid := auth.uid();

  -- Rate limit
  IF NOT check_rate_limit(uid, 'update_match_progress', 60) THEN
    RAISE EXCEPTION 'Rate limit exceeded. Please slow down.';
  END IF;

  -- Fetch match with row lock to prevent concurrent score corruption
  SELECT * INTO m FROM matches WHERE id = match_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Match not found'; END IF;
  IF m.player1_id != uid AND m.player2_id != uid THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  -- Validate player number
  IF player_num NOT IN (1, 2) THEN
    RAISE EXCEPTION 'player_num must be 1 or 2';
  END IF;

  -- Validate and score each answer against the stored questions.
  -- Deduplicate by questionIndex (keep the last occurrence so re-submissions
  -- are handled correctly without double-counting).
  FOR dedup_record IN
    WITH indexed AS (
      SELECT
        (elem->>'questionIndex')::int AS q_idx,
        (elem->>'answer')::int AS s_answer,
        (elem->>'timeTaken')::numeric AS t_taken,
        row_number() OVER () AS rn
      FROM jsonb_array_elements(answers) AS elem
    )
    SELECT DISTINCT ON (q_idx) q_idx, s_answer, t_taken
    FROM indexed
    WHERE q_idx IS NOT NULL
      AND q_idx >= 0
      AND q_idx < jsonb_array_length(m.questions)
    ORDER BY q_idx, rn DESC
  LOOP
    correct_answer := (m.questions->dedup_record.q_idx->>'answer')::int;
    submitted_answer := dedup_record.s_answer;
    ans_time_taken := dedup_record.t_taken;

    IF submitted_answer IS NOT NULL AND submitted_answer = correct_answer THEN
      correct_count := correct_count + 1;
    END IF;

    validated_answers := validated_answers || jsonb_build_object(
      'questionIndex', dedup_record.q_idx,
      'answer', submitted_answer,
      'isCorrect', (submitted_answer IS NOT NULL AND submitted_answer = correct_answer),
      'timeTaken', ans_time_taken
    );
  END LOOP;

  -- Store validated results (server-computed score replaces any client value)
  IF player_num = 1 THEN
    UPDATE matches
    SET scores = COALESCE(scores, '{}'::jsonb) || jsonb_build_object(
      'player1', correct_count,
      'player1_answers', validated_answers,
      'player1_done', player_done
    )
    WHERE id = match_id;
  ELSE
    UPDATE matches
    SET scores = COALESCE(scores, '{}'::jsonb) || jsonb_build_object(
      'player2', correct_count,
      'player2_answers', validated_answers,
      'player2_done', player_done
    )
    WHERE id = match_id;
  END IF;
END;
$$;
